- ignore: {name: "Use <$>"}
- warn: {name: "Use explicit module export list"}
- warn: {name: "Use fewer imports"}
- warn: {name: "Use fewer LANGUAGE pragmas"}
- warn: {name: "Unused LANGUAGE pragma"}
- warn: {name: "Use DerivingStrategies"}
- ignore: {name: "Use newtype instead of data"}
- modules:
  - {name: [PlutusTx.Prelude], as: PlutusTx, message: "You would make the MLabs styleguide happy."}
  - {name: [Prelude], as: Hask, message: "You would make the MLabs styleguide happy."}
